[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"
[lib]
name = "aoc"
path = "src/lib.rs"

[[bin]]
name = "aoc"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.6", features = ["cargo"] }
itertools = "0.13.0"
md5 = "0.7.0"
